[tool.black]
line-length = 120
target-version = ["py311"]

[tool.flake8]
inline-quotes = "double"
ignore = "E203, W503"
max-line-length = 120

[tool.isort]
profile = "black"
default_section = "THIRDPARTY"
force_single_line = true
line_length = 120
use_parentheses = true
py_version=311

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true

[tool.mypy]
plugins = [
  "pydantic.mypy",
  "sqlalchemy.ext.mypy.plugin",
]
ignore_missing_imports = true
follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = false
check_untyped_defs = true
no_implicit_reexport = true
show_error_codes = true

[bandit]
exclude = "tests"
skips = "B101, B601"