"""add pass log

Revision ID: 133f549eb285
Create Date: 2023-06-10 16:50:09.360703

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "133f549eb285"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pass_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "content_type",
            sa.Enum("POLL", "NOVELTY", name="contenttypeenum"),
            nullable=False,
        ),
        sa.Column("earned_points", sa.Integer(), nullable=False, default=0),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("PASSED", "FAILED", name="passstatusenum"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pass_logs")
    sa.Enum(name="passstatusenum").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="contenttypeenum").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
