"""link_pass_log_with_user

Revision ID: 680354bd616f
Revises: 11c3e4c36ae1
Create Date: 2024-05-13 18:10:48.241361

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "680354bd616f"
down_revision = "11c3e4c36ae1"
branch_labels = None
depends_on = None

pass_log_table = sa.table(
    "pass_logs",
    sa.column("id"),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    delete_pass_logs_stmt = pass_log_table.delete()
    op.execute(delete_pass_logs_stmt)

    op.add_column("pass_logs", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        op.f("fk_pass_logs_user_id_users"),
        "pass_logs",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )

    op.add_column(
        "pass_logs",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "pass_logs",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("pass_logs", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.drop_column("pass_logs", "updated")
    op.drop_column("pass_logs", "created")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    delete_pass_logs_stmt = pass_log_table.delete()
    op.execute(delete_pass_logs_stmt)

    op.drop_constraint(op.f("fk_pass_logs_user_id_users"), "pass_logs", type_="foreignkey")
    op.drop_column("pass_logs", "user_id")

    op.add_column(
        "pass_logs",
        sa.Column(
            "created",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "pass_logs",
        sa.Column(
            "updated",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("pass_logs", "deleted_at")
    op.drop_column("pass_logs", "updated_at")
    op.drop_column("pass_logs", "created_at")
    # ### end Alembic commands ###
